### PR TITLE
Make $bugsnagWordpress global

### PR DESCRIPTION
**Pull request by fiskhandlarn**
...for mu-plugins inclusion (with WordPlate for example: https://github.com/wordplate/framework/blob/master/src/PluginLoader.php)

### CODE REVIEW

**Comment by tomlongridge** [comment]
@fiskhandlarn - I have managed to successfully run Bugsnag from mu-plugins (using a load script with code in a `/bugsnag` subdirectory (e.g. https://www.sitepoint.com/wordpress-mu-plugins/) without explicitly making the variable global. Did you do similar and encounter issues?

**Comment by tomlongridge** [comment]
Having read #23, I can see this would be useful for this so I'm including in #40 .

**Comment by fiskhandlarn** [comment]
Maybe I was unclear. X) Making `$bugsnagWordpress` global is not a requirement for `mu-plugins` inclusions. I would like to have it global so I can access it like below. A singleton getter in the `Bugsnag_Wordpress` would work just as fine. Please reopen. :)

```
if (!function_exists('bugsnag_error')) {
    function bugsnag_error($name, $message, array $metaData = null, $severity = null)
    {
        if (!env('DISABLE_BUGSNAG')) {
            if (class_exists('Bugsnag_Wordpress')) {
                global $bugsnagWordpress;

                if (isset($bugsnagWordpress)) {
                    $bugsnagWordpress->notifyError($name, $message, $metaData, $severity);
                }
            }
        }
    }
}

if (class_exists('Bugsnag_Wordpress')) {
    if (env('DISABLE_BUGSNAG')) {
        // https://github.com/bugsnag/bugsnag-wordpress/issues/27#issuecomment-458890694
        restore_error_handler();
        restore_exception_handler();
    } else {
        global $bugsnagWordpress;

        if (isset($bugsnagWordpress)) {
            // Bugsnag reports PHP warnings for code that is silenced with an @.
            // https://github.com/bugsnag/bugsnag-wordpress/issues/35#issuecomment-457130639
            $bugsnagWordpress->setBeforeNotifyFunction(function ($report) {
                if (error_reporting() === 0) {
                    return false;
                }
            });
        }
    }
}
```

**Comment by tomlongridge** [comment]
@fiskhandlarn - in the end, I noticed that the global declaration was also requested for use in a CLI script, so I included it in the latest release that I shipped yesterday.

https://github.com/bugsnag/bugsnag-wordpress/releases/tag/v1.4.0

**Comment by fiskhandlarn** [comment]
Ah good, I thought it was for CLI use only. Nevermind then, and thanks! :)

**Pull request closed without merging**
